"use client";
import { useState } from "react";
import Link from "next/link.js";
import { articlePreview, gamePreview } from "./demo-content.js";
import { EmptyState, Icon, PageIntro } from "./ui.js";

function PreviewBanner() { return <p className="preview-banner">ตัวอย่าง UI เท่านั้น · ใช้ข้อมูลสมมติ · ไม่เชื่อมระบบบทเรียน/เกม และไม่บันทึกผลหรือคะแนน</p>; }
export function GamesHome() {
  return <div className="space-y-6"><PageIntro eyebrow="INVESTIGATION LAB" title="เกมสืบสวน">พื้นที่สำหรับพิจารณาหลักฐานและฝึกตัดสินใจในคดีจำลอง</PageIntro><EmptyState title="ยังไม่มีคดีที่เปิดให้เล่น">ระบบเกมสืบสวนและผลประเมินยังอยู่ระหว่างพัฒนา ไม่ใช่สถานการณ์ AI ที่เปิดฝึกอยู่แล้ว</EmptyState><article className="panel"><span className="tag tag-neutral">ตัวอย่าง UI แยกจากคดีจริง</span><h2 className="mt-4">{gamePreview.title}</h2><p className="muted mt-3">{gamePreview.description}</p><Link className="button button-secondary mt-5" href="/games/preview">ดูตัวอย่างพื้นที่สืบสวน →</Link></article></div>;
}
export function GamePreview({ result = false }: { result?: boolean }) {
  const [evidence,setEvidence]=useState(gamePreview.evidence[0]!);
  const [choice,setChoice]=useState("");
  return <div className="space-y-6"><Link className="back-link" href="/games">← กลับหน้าเกมสืบสวน</Link><PageIntro eyebrow="UI PREVIEW · NO SCORING" title={result ? "ตัวอย่างหน้าสรุปเกม" : "ตัวอย่างพื้นที่ตรวจหลักฐาน"}>ไม่มีเกมจริงหรือการประเมินอยู่เบื้องหลังหน้าตัวอย่างนี้</PageIntro><PreviewBanner />{result ? <><div className="stat-grid">{["ผลประเมิน", "หลักฐานที่ตรวจพบ", "เวลาเล่น"].map(label=><div className="stat-card" key={label}><p>{label}</p><strong>—</strong><p>ยังไม่มีข้อมูลจากระบบเกม</p></div>)}</div><EmptyState title="ยังไม่มีผลการเล่น">ระบบประเมินเกมยังไม่เชื่อมต่อ จึงไม่แสดงคะแนน ความสำเร็จ หรือคำแนะนำที่แต่งขึ้น</EmptyState><Link className="button button-secondary" href="/games/preview">กลับไปดูตัวอย่างพื้นที่สืบสวน</Link></> : <><div className="preview-grid"><section className="panel"><h2>แฟ้มหลักฐานตัวอย่าง</h2><div className="filter-chips mt-5">{gamePreview.evidence.map(e=><button key={e.id} aria-pressed={evidence.id===e.id} onClick={()=>setEvidence(e)}>{e.title}</button>)}</div><div className="preview-evidence mt-5"><h3>{evidence.title}</h3><p className="whitespace-pre-line">{evidence.text}</p></div></section><section className="panel"><h2>ลองเลือกประเด็นที่จะตรวจ</h2><fieldset className="mt-5"><legend className="field-hint">การเลือกนี้อยู่เฉพาะหน้าตัวอย่างและไม่ถูกบันทึก</legend><div className="space-y-3 mt-4">{["ช่องทางติดต่อของผู้ส่ง", "รายละเอียดหน้าที่ในเอกสาร", "ยังต้องการข้อมูลเพิ่มเติม"].map(c=><label className="action-option" key={c}><input type="radio" name="preview-choice" checked={choice===c} onChange={()=>setChoice(c)}/><span>{c}</span></label>)}</div></fieldset><p className="field-hint mt-5" role="status">{choice ? "เลือกในตัวอย่าง: "+choice : "ยังไม่ได้เลือกประเด็น"}</p></section></div><Link className="button button-secondary" href="/games/preview/result">ดูโครงหน้าสรุปผล (ไม่มีคะแนน) →</Link></>}</div>;
}
export function KnowledgeHome() {
  const [query,setQuery]=useState("");
  const matches=(articlePreview.title+articlePreview.category).includes(query.trim());
  return <div className="space-y-6"><PageIntro eyebrow="KNOWLEDGE LIBRARY" title="คลังความรู้">พื้นที่สำหรับเรียนรู้และทบทวนแนวทางรับมือภัยออนไลน์</PageIntro><EmptyState title="ยังไม่มีบทเรียนที่เผยแพร่">ระบบคลังบทเรียนยังไม่เชื่อมต่อ รายการตัวอย่างด้านล่างไม่ใช่คลังบทเรียน 16 เรื่องตามแผนโครงงาน</EmptyState><section className="space-y-4" aria-label="ตัวอย่าง UI คลังความรู้"><PreviewBanner/><div className="search-field"><Icon name="search"/><label className="sr-only" htmlFor="article-search">ค้นหาในบทความตัวอย่าง</label><input id="article-search" type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="ค้นหาในบทความตัวอย่าง…" /></div>{matches ? <article className="panel"><span className="tag">{articlePreview.category} · ตัวอย่าง UI</span><h2 className="mt-4">{articlePreview.title}</h2><p className="muted mt-3">{articlePreview.description}</p><Link href="/knowledge/preview" className="text-link mt-4">เปิดหน้าอ่านตัวอย่าง →</Link></article> : <p role="status" className="muted">ไม่พบบทความตัวอย่างที่ตรงกับคำค้น</p>}</section></div>;
}
export function ArticlePreview() {
  return <div className="reading-page space-y-6"><Link className="back-link" href="/knowledge">← กลับคลังความรู้</Link><PreviewBanner/><article className="panel"><span className="tag">{articlePreview.category} · ตัวอย่าง UI</span><h1 className="mt-5">{articlePreview.title}</h1><p className="muted mt-3">{articlePreview.description}</p><div className="reading-art" aria-hidden="true"><Icon name="book"/></div>{articlePreview.sections.map(s=><section key={s.title}><h2>{s.title}</h2><p>{s.text}</p></section>)}<Link className="button mt-6" href="/scenarios">เลือกสถานการณ์ที่เปิดให้ฝึกจริง</Link></article></div>;
}
